version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - '/mnt/data:/data/db'
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  server:
    image: lucasurzedo/anyjs:1.0
    depends_on:
      - mongo
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==worker"
    volumes:
      - anyjs:/data
    environment:
      CLUSTER_SIZE: 4
      JAVA_CLUSTER_SIZE: 8
    ports:
      - "4445:4445"

  server_java:
    image: lucasurzedo/anyjs-java:1.0
    depends_on:
      - mongo
    deploy:
      replicas: 8
      placement:
        constraints:
          - "node.role==worker"
    volumes:
      - anyjs:/data
    ports:
      - "4545:4545"

  observer:
    image: lucasurzedo/anyjsobserver:1.0
    deploy:
      placement:
        constraints:
          - "node.role==worker"
    ports:
      - "4447:4447"

  gatewayapi:
    image: devopsfaith/krakend:2
    volumes:
      - ./src/microservices/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "80:8080"
      - "8090:8090"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]

volumes:
  anyjs:
